"""The explorer keeps its shape analysis and loses its account numbers.

These tests assert what a READER SEES, not which constant a field maps
to. Asserting the level name would only restate the registry, so every
split or rename of a level would fail every test that mentioned it while
the page behaved identically - a change-detector rather than a check.
Adding fields, or reorganising levels, should break nothing here unless
somebody's account number starts appearing on a page.

Sensitivity follows the COST OF ROTATION: an identifier obdi mints is
regenerated by a rebuild, one a provider mints is opaque outside their
system, and a sort code can be changed only by closing the account.
"""

from __future__ import annotations

import pytest

from obdi.classification import (
    CATEGORICAL_LIMIT,
    FIELD_CAVEATS,
    KNOWN_FIELDS,
    caveat_for,
    description_for,
    redact_summary,
)


def shown(path: str, **extra: object) -> dict[str, object]:
    """Render one field through the allowlist and report what survived."""
    field: dict[str, object] = {
        "path": path,
        "present": 3,
        "types": ["string"],
        "distinct": 2,
        "values": [{"value": "SECRETVALUE", "count": 1}],
    }
    field.update(extra)
    return redact_summary({"fields": [field]})["fields"][0]


def leaked(field: dict[str, object]) -> bool:
    return "SECRETVALUE" in str(field)


class TestWithholdingIsTheDefault:
    def test_AFieldNoSpecDescribes_IsWithheld_AndReadsAsNews(self):
        """The allowlist's whole point, plus a distinction worth having:
        a field nobody has ever documented is not a gap in our work, it
        is the provider sending something new."""
        field = shown("brand_new_provider_field")

        assert leaked(field) is False
        assert "may have started sending something new" in str(field["note"])

    def test_ADocumentedButUnjudgedField_SaysThatInstead(self):
        """Known to exist, nobody has decided about it. Different fact,
        different sentence - and the classification work stays optional."""
        field = shown("consent_status")

        assert leaked(field) is False
        assert "nobody has classified this field yet" in str(field["note"])

    def test_WithholdingKeepsTheShapeThePageExistsToShow(self):
        field = shown(
            "brand_new_provider_field",
            length={"min": 13, "max": 13},
            format="hex",
        )

        assert field["present"] == 3
        assert field["types"] == ["string"]
        assert field["length"] == {"min": 13, "max": 13}
        assert field["format"] == "hex"

    def test_TheSummarySaysHowMuchItWithheld_SoRedactionIsVisible(self):
        summary = {
            "fields": [
                {"path": "account_number.number", "values": [{"value": "1", "count": 1}]},
                {"path": "brand_new_field", "values": [{"value": "2", "count": 1}]},
                {"path": "currency", "values": [{"value": "GBP", "count": 1}]},
            ]
        }

        result = redact_summary(summary)

        assert result["withheld_fields"] == 2
        assert result["unclassified_fields"] == 1


class TestSensitivityFollowsTheCostOfRotation:
    @pytest.mark.parametrize(
        "path",
        [
            "account_number.number",
            "account_number.sort_code",
            "account_number.iban",
            "accountIdentifier",
            "bankIdentifier",
            "iban",
        ],
    )
    def test_APermanentIdentifierNeverReachesThePage(self, path):
        assert leaked(shown(path)) is False

    @pytest.mark.parametrize(
        "path",
        ["account_id", "accountUid", "transaction_id", "feedItemUid", "entity_id"],
    )
    def test_ARotatableIdentifierIsShown(self, path):
        """Opaque outside the provider, regenerable inside obdi, and
        already printed in bind boxes and feeder lines on every page -
        withholding it here would conceal nothing and cost the debugging
        the explorer exists for."""
        assert leaked(shown(path)) is True

    def test_ThePermanentAndTheRotatableAreTreatedDifferently(self):
        """The axis itself, stated once: this is the design decision, so
        it is worth pinning even though the level names are not."""
        assert leaked(shown("accountIdentifier")) is False
        assert leaked(shown("accountUid")) is True


class TestPeopleAndFreeTextSayWhyTheyAreWithheld:
    @pytest.mark.parametrize("path", ["display_name", "name_on_card", "merchant_name"])
    def test_PeopleAreWithheld(self, path):
        field = shown(path)

        assert leaked(field) is False
        assert "identifies a person" in str(field["note"])

    @pytest.mark.parametrize("path", ["description", "reference"])
    def test_FreeTextIsWithheld_BecauseNothingConstrainsIt(self, path):
        field = shown(path)

        assert leaked(field) is False
        assert "free text" in str(field["note"])


class TestCredentialsAreAnIncidentRatherThanADisplayQuestion:
    @pytest.mark.parametrize("path", ["access_token", "refresh_token", "client_secret"])
    def test_ACredentialInStoredEvidence_IsWithheldAndCalledOut(self, path):
        """These live in the credential store and must never reach a
        landed payload. If one is here, the question is not how to render
        it."""
        field = shown(path)

        assert leaked(field) is False
        assert "should never appear in stored evidence" in str(field["note"])


class TestAClosedSetSaysSoAndIsChecked:
    @pytest.mark.parametrize(
        "path", ["transaction_type", "transaction_category", "status", "direction"]
    )
    def test_AnEnumerationIsShownInFull(self, path):
        assert leaked(shown(path)) is True

    def test_AClosedSetThatIsNotClosed_IsWithheldAndReported(self):
        """Declaring cardinality makes misclassification detectable: a
        closed set holding thousands of values is either classified wrong
        or the provider changed, and rendering them all is the one
        response wrong under both readings."""
        field = shown("status", distinct=CATEGORICAL_LIMIT + 1)

        assert leaked(field) is False
        assert "classified as a closed set" in str(field["note"])


class TestTheProvidersOwnRedactionIsAttributedToThem:
    def test_APartialCardNumberIsShown_AndLabelledAsTheirChoice(self):
        """Masking it like something we chose to hide would misrepresent
        what the provider sent, which is what this page is for."""
        field = shown("partial_card_number")

        assert leaked(field) is True
        assert "not redacted by obdi" in str(field["note"])


class TestMoneyKeepsItsRangeAndLosesItsItems:
    def test_AmountsShowTheirSpanButNotEachTransaction(self):
        field = shown("amount", min=-120.5, max=2400.0)

        assert leaked(field) is False
        assert field["min"] == -120.5
        assert field["max"] == 2400.0
        assert "individual amounts" in str(field["note"])


class TestDescriptiveFieldsSurviveIntact:
    @pytest.mark.parametrize(
        "path", ["currency", "country", "provider.provider_id", "timestamp"]
    )
    def test_TheFieldsThePageExistsToShow_AreShownInFull(self, path):
        assert leaked(shown(path)) is True


class TestNestingAndPrefixes:
    def test_ANestedFieldIsJudgedWithoutClaimingEveryLeafOfThatName(self):
        assert leaked(shown("account_number.number")) is False
        assert leaked(shown("page.number")) is False  # unknown, so withheld

    def test_ACurrencyInsideANestedBalanceIsStillJustACurrency(self):
        assert leaked(shown("running_balance.currency")) is True

    def test_TheCommonPrefixIsDropped_BecauseForOneAccountItIsTheNumber(self):
        """The subtlest leak on the page: a "common prefix" computed over
        a single account's payload is that account's number."""
        field = shown(
            "account_number.number",
            prefix="SECRETVALUE",
            min="SECRETVALUE",
            max="SECRETVALUE",
            format="8 digits",
        )

        assert leaked(field) is False
        assert field["format"] == "8 digits"


class TestTheEnumerationIsBroadEnoughToBeUseful:
    def test_TheDocumentedSurfaceIsRegistered_NotJustWhatWeHaveSeen(self):
        """Generated from the provider spec rather than from observation,
        so a field our accounts never happened to return is still known
        to exist rather than reading as news."""
        for path in ("consent_status", "meta.user_comments", "credit_limit"):
            assert path in KNOWN_FIELDS


class TestTheProvidersOwnCaveatsTravelWithTheField:
    """A warning nobody reads is a defect waiting to be written.

    "transaction_id may change between requests" was in the spec the
    whole time; using it as the tier-one identity key duplicated money on
    re-fetch. The sentence is more useful beside the field than in a
    document nobody opens at the moment they need it.
    """

    def test_TheFieldThatCausedTheDefect_CarriesItsWarning(self):
        caveat = caveat_for("transaction_id")

        assert caveat
        assert "change" in caveat.lower()

    def test_ACaveatRidesOnTheRenderedField_SoItIsSeenInPlace(self):
        field = shown("transaction_id")

        assert "change" in str(field["caveat"]).lower()

    def test_AFieldWithNoWarning_CarriesNone_RatherThanAnEmptyOne(self):
        """Silence has to mean something: a caveat on every row would be
        noise, and noise is how a real warning gets skipped."""
        assert caveat_for("currency") == ""
        assert "caveat" not in shown("currency")

    def test_CaveatsAreDetectedByLanguage_NotCuratedOneByOne(self):
        """So a warning a future spec adds is caught by the same rule
        that caught this one, rather than waiting for somebody to notice."""
        assert len(FIELD_CAVEATS) > 1
        assert all(
            any(
                phrase in text.lower()
                for phrase in ("change", "guarantee", "deprecat", "not be", "not use")
            )
            for text in FIELD_CAVEATS.values()
        )

    def test_TheProvidersDescriptionIsAvailableInTheirOwnWords(self):
        """Not a paraphrase: a paraphrase would be our claim about their
        field, and would silently rot when they revised it."""
        assert description_for("transaction_id")
        assert description_for("description")
        # Not every field carries one, and inventing prose to fill the gap
        # would be our words wearing the provider's authority.
        assert description_for("currency") == ""
