"""The explorer keeps its shape analysis and loses its account numbers.

Sensitivity here follows the COST OF ROTATION. An identifier obdi mints
can be regenerated by a rebuild; one a provider mints is opaque outside
their system and could be reissued by them; a sort code and account
number can be changed only by closing the account. Those are three
different risks, and treating them alike would either leak the worst or
uselessly hide the harmless.
"""

from __future__ import annotations

import pytest

from obdi.classification import (
    CATEGORICAL,
    CATEGORICAL_LIMIT,
    NARRATIVE,
    OPAQUE_ID,
    PERMANENT_ID,
    PERSONAL,
    PROVIDER_PARTIAL,
    RANGE_ONLY,
    SHOW,
    UNCLASSIFIED,
    classify,
    redact_summary,
)


class TestTheDefaultIsToWithhold:
    def test_AFieldNobodyHasClassified_IsWithheld_AndSaysSo(self):
        """The whole reason for an allowlist: a field a provider adds
        tomorrow must not render in full because nobody thought about it."""
        assert classify("some_new_provider_field") == UNCLASSIFIED

    def test_AnUnclassifiedFieldLosesItsValues_ButKeepsItsShape(self):
        summary = {
            "fields": [
                {
                    "path": "surprise_field",
                    "present": 3,
                    "types": ["string"],
                    "distinct": 3,
                    "values": [{"value": "a-real-secret", "count": 1}],
                    "length": {"min": 13, "max": 13},
                }
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert "values" not in field
        assert field["present"] == 3
        assert field["length"] == {"min": 13, "max": 13}
        assert "not yet classified" in field["note"]

    def test_TheSummaryCountsWhatItWithheld_SoTheGapIsVisible(self):
        summary = {
            "fields": [
                {"path": "account_number.number", "values": [{"value": "1", "count": 1}]},
                {"path": "brand_new_field", "values": [{"value": "2", "count": 1}]},
                {"path": "currency", "values": [{"value": "GBP", "count": 1}]},
            ]
        }

        result = redact_summary(summary)

        assert result["withheld_fields"] == 2
        assert result["unclassified_fields"] == 1


class TestSensitivityFollowsTheCostOfRotation:
    @pytest.mark.parametrize(
        "path",
        [
            "account_number.number",
            "account_number.sort_code",
            "account_number.iban",
            "accountIdentifier",
            "bankIdentifier",
            "iban",
        ],
    )
    def test_APermanentIdentifierIsWithheld(self, path):
        """It outlives any breach; changing it means closing the account."""
        assert classify(path) == PERMANENT_ID

    @pytest.mark.parametrize(
        "path",
        [
            "account_id",
            "accountUid",
            "categoryUid",
            "transaction_id",
            "feedItemUid",
            "entity_id",
            "content_key",
        ],
    )
    def test_ARotatableIdentifierIsShown(self, path):
        """Opaque outside the provider, regenerable inside obdi, and
        already rendered in bind boxes and feeder lines on every page -
        so withholding it HERE would be incoherent and would make the
        explorer useless for the debugging it exists for."""
        assert classify(path) == OPAQUE_ID

    def test_ARotatableIdentifierKeepsItsValues(self):
        summary = {
            "fields": [
                {"path": "accountUid", "values": [{"value": "abc-123", "count": 1}]}
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert field["values"] == [{"value": "abc-123", "count": 1}]
        assert "note" not in field

    def test_ThePermanentAndRotatableCases_AreNotTheSameLevel(self):
        assert classify("accountIdentifier") != classify("accountUid")


class TestPeopleAndFreeTextAreWithheldForDifferentReasons:
    @pytest.mark.parametrize(
        "path", ["display_name", "name_on_card", "counterPartyName", "merchant_name"]
    )
    def test_PeopleAreWithheld(self, path):
        assert classify(path) == PERSONAL

    @pytest.mark.parametrize("path", ["description", "reference"])
    def test_FreeTextIsWithheld_BecauseNothingConstrainsIt(self, path):
        assert classify(path) == NARRATIVE

    def test_EachSaysWhyRatherThanJustThatItIsHidden(self):
        summary = {
            "fields": [
                {"path": "display_name", "values": [{"value": "A Name", "count": 1}]},
                {"path": "reference", "values": [{"value": "a note", "count": 1}]},
            ]
        }

        fields = redact_summary(summary)["fields"]

        assert "identifies a person" in fields[0]["note"]
        assert "free text" in fields[1]["note"]


class TestAClosedSetSaysSoAndIsChecked:
    @pytest.mark.parametrize(
        "path",
        [
            "transaction_type",
            "transaction_category",
            "status",
            "direction",
            "card_type",
            "account_type",
        ],
    )
    def test_KnownEnumerationsAreCategorical(self, path):
        assert classify(path) == CATEGORICAL

    def test_ACategoricalFieldKeepsItsValuesAndCounts(self):
        summary = {
            "fields": [
                {
                    "path": "transaction_category",
                    "distinct": 2,
                    "values": [
                        {"value": "DIRECT_DEBIT", "count": 12},
                        {"value": "PURCHASE", "count": 40},
                    ],
                }
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert len(field["values"]) == 2
        assert "note" not in field

    def test_AClosedSetThatIsNotClosed_IsWithheldAndReported(self):
        """Declaring cardinality makes misclassification detectable: a
        field claimed to be a closed set with thousands of values is
        either misclassified or the provider changed something, and
        either way rendering them all would be the wrong response."""
        summary = {
            "fields": [
                {
                    "path": "status",
                    "distinct": CATEGORICAL_LIMIT + 1,
                    "values": [{"value": "anything", "count": 1}],
                }
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert "values" not in field
        assert field["disclosure"] == UNCLASSIFIED
        assert "classified as a closed set" in field["note"]


class TestTheProvidersOwnRedactionIsLabelledAsTheirs:
    def test_APartialCardNumberIsShown_AndAttributedToTheProvider(self):
        """It arrived partial. Masking it like something we chose to hide
        would misrepresent what the provider sent, which is the one thing
        this page exists to show."""
        assert classify("partial_card_number") == PROVIDER_PARTIAL

        summary = {
            "fields": [
                {"path": "partial_card_number", "values": [{"value": "8484", "count": 1}]}
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert field["values"] == [{"value": "8484", "count": 1}]
        assert "not redacted by obdi" in field["note"]


class TestMoneyKeepsItsRangeAndLosesItsItems:
    def test_AmountsShowTheirSpanButNotEachTransaction(self):
        assert classify("amount") == RANGE_ONLY

        summary = {
            "fields": [
                {
                    "path": "amount",
                    "min": -120.5,
                    "max": 2400.0,
                    "values": [{"value": "-120.5", "count": 1}],
                }
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert field["min"] == -120.5
        assert field["max"] == 2400.0
        assert "values" not in field
        assert "individual amounts withheld" in field["note"]


class TestDescriptiveFieldsSurviveIntact:
    @pytest.mark.parametrize(
        "path", ["currency", "country", "provider.provider_id", "timestamp"]
    )
    def test_TheFieldsTheExplorerExistsToShow_AreShownInFull(self, path):
        assert classify(path) == SHOW


class TestNestingAndPrefixes:
    def test_ANestedFieldIsClassifiedWithoutClaimingEveryLeafOfThatName(self):
        assert classify("account_number.number") == PERMANENT_ID
        assert classify("page.number") == UNCLASSIFIED

    def test_ACurrencyInsideANestedBalanceIsStillJustACurrency(self):
        assert classify("running_balance.currency") == SHOW
        assert classify("running_balance.amount") == RANGE_ONLY

    def test_TheCommonPrefixIsDropped_BecauseForOneAccountItIsTheNumber(self):
        """The subtlest leak on the page: a "common prefix" computed over
        a single account's payload is that account's number."""
        summary = {
            "fields": [
                {
                    "path": "account_number.number",
                    "present": 1,
                    "types": ["string"],
                    "prefix": "12345678",
                    "min": "12345678",
                    "max": "12345678",
                    "values": [{"value": "12345678", "count": 1}],
                    "format": "8 digits",
                }
            ]
        }

        field = redact_summary(summary)["fields"][0]

        assert "12345678" not in str(field)
        assert field["format"] == "8 digits"
        assert field["types"] == ["string"]
