"""What may be shown, decided per field, by allowlist.

The raw explorer's job is to let a person see what a provider actually
sent - shape, nesting, types, formats, cardinality - and that job is
worth keeping. What it must stop doing is printing account numbers on a
page that gets opened twenty times a day and screenshotted.

A DENYLIST cannot do this. Masking the fields known to be sensitive
fails open: the next field a provider adds, or the first field from a
provider not yet integrated, renders in full because nobody thought
about it. The asymmetry decides the design - a wrongly-withheld field is
an annoyance, a wrongly-revealed account number cannot be un-revealed,
and unlike an API key it cannot be rotated afterwards either.

So every field is classified, the default is to withhold, and a test
fails when evidence contains a path nobody has classified. The painful
part is the first enumeration; drift after that is caught mechanically
rather than by vigilance.

The distinction between "arrived redacted" and "we redacted it" is
load-bearing rather than cosmetic. A partial card number is the
PROVIDER's disclosure decision and is evidence about them; masking it
the same way we mask a number we chose to hide would misrepresent what
they sent, which is the one property this explorer exists to preserve.
"""

from __future__ import annotations

import re

#: Safe in full: types, currencies, timestamps - values that describe the
#: record rather than identify a person or an account.
SHOW = "show"
#: A closed set of known values - DEBIT/CREDIT, a status, a category. Safe
#: for a different reason from SHOW: the value set is public knowledge and
#: says only which bucket a record fell into. Declaring it also makes
#: misclassification DETECTABLE - a field claimed categorical whose
#: observed cardinality is large is either wrong or the provider changed
#: something, and either way somebody should look.
CATEGORICAL = "categorical"
#: An identifier that CAN be rotated: one we mint ourselves (regenerated by
#: a rebuild) or one the provider mints (opaque, meaningful only inside
#: their system). Shown, because the cost of exposure is proportional to
#: the cost of rotation - and because these already appear throughout the
#: UI in bind boxes and feeder lines, so withholding them HERE would be
#: incoherent as well as useless for debugging.
OPAQUE_ID = "opaque-id"
#: Ranges and formats only. Monetary values: the span and the precision are
#: what a person is reading the shape page FOR, but the individual amounts
#: are their spending.
RANGE_ONLY = "range-only"
#: Structure only - presence, types, length, format. Never a value, and
#: never a common prefix: for a single-account payload the prefix IS the
#: account number.
SHAPE_ONLY = "shape-only"
#: A real-world identifier that CANNOT be rotated: a sort code and account
#: number outlive any breach, and changing one means closing the account.
#: The opposite end of the axis from OPAQUE_ID, and the reason the two are
#: treated differently despite both being "identifiers".
PERMANENT_ID = "permanent-id"
#: A person: names, addresses, contact details.
PERSONAL = "personal"
#: Free text a human wrote. Withheld not because of what it usually says
#: but because nothing constrains what it CAN say - a reference field is
#: exactly where somebody types what they would not choose to publish.
NARRATIVE = "narrative"
#: Arrived already redacted. Shown as sent, and labelled as the provider's
#: choice rather than ours.
PROVIDER_PARTIAL = "provider-partial"
#: Nobody has classified this yet, so it is withheld and says so loudly.
UNCLASSIFIED = "unclassified"

#: Field paths, by the last segment unless a full path is given. Patterns
#: are matched against the whole dotted path first, then the leaf, so a
#: nested "account_number.number" can be classified without also claiming
#: every field called "number" everywhere.
_RULES: list[tuple[str, str]] = [
    # --- permanent: rotation means closing the account ---
    (r"^account_number\.(number|sort_code|iban|swift_bic)$", PERMANENT_ID),
    (r"^(iban|bic|swift_bic)$", PERMANENT_ID),
    (r"^(accountIdentifier|bankIdentifier)$", PERMANENT_ID),
    (r"^counterPartySubEntity(Identifier|SubIdentifier)$", PERMANENT_ID),
    # --- rotatable: opaque outside the provider, and already rendered
    # --- elsewhere on every page ---
    (r"^running_balance\.currency$", SHOW),
    (r"^(account_id|accountUid|categoryUid|defaultCategory)$", OPAQUE_ID),
    (r"^(transaction_id|provider_transaction_id)$", OPAQUE_ID),
    (r"^normalised_provider_transaction_id$", OPAQUE_ID),
    (r"^(feedItemUid|counterPartyUid|counterPartySubEntityUid)$", OPAQUE_ID),
    (r"^(entity_id|content_key|imported_id|digest)$", OPAQUE_ID),
    # --- people ---
    (r"^(display_name|name|name_on_card)$", PERSONAL),
    (r"^(counterPartyName|counterPartySubEntityName|merchant_name)$", PERSONAL),
    (r"^meta\.provider_merchant_name$", PERSONAL),
    (r"^meta\.address$", PERSONAL),
    # --- free text: unbounded by construction ---
    (r"^(description|reference)$", NARRATIVE),
    (r"^meta\.provider_reference$", NARRATIVE),
    # --- the provider's own redaction, kept and labelled as theirs ---
    (r"^partial_card_number$", PROVIDER_PARTIAL),
    # --- money: the range and the precision, not the individual amounts ---
    (r"^amount$", RANGE_ONLY),
    (r"^amount\.(minorUnits|currency)$", RANGE_ONLY),
    (r"^running_balance\.amount$", RANGE_ONLY),
    (r"^(sourceAmount|totalFeeAmount)\..*$", RANGE_ONLY),
    # --- descriptive: safe in full ---
    (r"^(currency|country)$", SHOW),
    (r"^(account_type|accountType|card_type|card_network)$", CATEGORICAL),
    (r"^(transaction_type|transaction_category|status|direction|source)$", CATEGORICAL),
    (r"^transaction_classification.*$", CATEGORICAL),
    (r"^(spendingCategory|hasAttachment|hasReceipt)$", CATEGORICAL),
    (r"^provider\.(provider_id|display_name|logo_uri)$", SHOW),
    (r"^(timestamp|update_timestamp|createdAt|updatedAt)$", SHOW),
    (r"^(transactionTime|settlementTime|retryAllocationUntilTime)$", SHOW),
    (r"^meta\.provider_category$", SHOW),
    (r"^(booked|pending|results|accounts|savingsGoals|feedItems)$", SHOW),
]

_COMPILED = [(re.compile(pattern), level) for pattern, level in _RULES]


def classify(path: str) -> str:
    """How much of this field may be shown. Withholds by default."""
    leaf = path.rsplit(".", 1)[-1]
    for pattern, level in _COMPILED:
        if pattern.match(path) or pattern.match(leaf):
            return level
    return UNCLASSIFIED


#: What each level says about itself on the page. Written for a reader who
#: wants to know WHY a value is missing, since "no value" and "withheld"
#: are different facts about the payload.
NOTES = {
    SHAPE_ONLY: "values withheld - identifying or personal",
    PERMANENT_ID: (
        "withheld - a permanent identifier; it cannot be rotated, only "
        "outlived by closing the account"
    ),
    PERSONAL: "withheld - identifies a person",
    NARRATIVE: "withheld - free text, so nothing constrains what it may say",
    RANGE_ONLY: "range shown, individual amounts withheld",
    PROVIDER_PARTIAL: "partial as sent by the provider, not redacted by obdi",
    UNCLASSIFIED: "withheld - this field is not yet classified",
}

#: Above this, a field claiming to be a closed set is not behaving like
#: one. Chosen to sit above any real enumeration seen so far (transaction
#: categories top out around twenty) and well below free text.
CATEGORICAL_LIMIT = 64

#: Keys in a field summary that carry actual values rather than shape.
_VALUE_KEYS = ("values", "min", "max", "prefix")
#: Keys that carry a value but are a legitimate RANGE.
_RANGE_KEYS = ("min", "max")


def redact_summary(summary: dict[str, object]) -> dict[str, object]:
    """Apply the allowlist to a computed shape summary.

    Deliberately a post-pass rather than a change to the analysis: the
    shape - nesting, types, presence, formats, cardinality - is exactly
    what the explorer is for and is computed the same way it always was.
    Only the example VALUES are gated.
    """
    raw_fields = summary.get("fields")
    if not isinstance(raw_fields, list):
        return summary

    fields: list[dict[str, object]] = []
    withheld = 0
    unclassified = 0
    for entry in raw_fields:
        if not isinstance(entry, dict):
            continue
        field = dict(entry)
        level = classify(str(field.get("path", "")))
        field["disclosure"] = level
        if level == CATEGORICAL:
            # A closed set that is not closed is a classification error,
            # and saying so beats quietly rendering a thousand values.
            distinct = int(str(field.get("distinct", 0) or 0))
            if distinct > CATEGORICAL_LIMIT:
                for key in _VALUE_KEYS:
                    field.pop(key, None)
                field["note"] = (
                    f"withheld - classified as a closed set but {distinct} "
                    "distinct values observed, so the classification is "
                    "wrong or the provider changed"
                )
                field["disclosure"] = UNCLASSIFIED
                withheld += 1
                unclassified += 1
                fields.append(field)
                continue
        if level in (SHAPE_ONLY, PERMANENT_ID, PERSONAL, NARRATIVE, UNCLASSIFIED):
            for key in _VALUE_KEYS:
                field.pop(key, None)
            withheld += 1
            if level == UNCLASSIFIED:
                unclassified += 1
        elif level == RANGE_ONLY:
            # The span survives; the itemised list of a person's amounts
            # does not.
            field.pop("values", None)
            field.pop("prefix", None)
        if level in NOTES:
            field["note"] = NOTES[level]
        fields.append(field)

    result = dict(summary)
    result["fields"] = fields
    result["withheld_fields"] = withheld
    result["unclassified_fields"] = unclassified
    return result


def known_paths() -> set[str]:
    """Every path shape the registry currently claims to understand.

    Used by the coverage test, which reads real evidence and fails when a
    field arrives that nobody has classified - so the enumeration stays
    honest without anyone having to remember to revisit it.
    """
    return {pattern.pattern for pattern, _ in _COMPILED}
